# -*- coding: utf-8 -*-
# Copyright © 2025, Broadcom, Inc.  All rights reserved.
# SPDX-License-Identifier: BSD-2-Clause

# Example Django application under 3.0
# django-yamlconf is functional against Django 2.0 but the example app
# has been removed: GitHub issued security alerts for this version of
# Django.  Older releases of the module (1.4.0 or older contain this
# example code, if needed).

clean:
	$(MAKE) -C django-4 $@
