# -*- coding: utf-8 -*-
# Copyright © 2018, VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: BSD-2-Clause

# Example Django application under both 1.11 and 2.0

clean:
	$(MAKE) -C django-2.0 $@
	$(MAKE) -C django-1.11 $@
